const moodTexts = [
  "you got this, cutie",
  "you are glowing softly",
  "keep going, cutie",
  "your vibe is safe here",
  "you make quiet moments pretty",
  "small steps still count, cutie",
  "you are doing better than you think",
  "soft heart, strong soul",
  "you deserve a gentle minute",
  "your smile would fix the sky",
  "keep your chin up, cutie",
  "you are someone's favorite pause",
  "breathe easy, you are okay",
  "today can still be sweet",
  "you bring calm to the room",
  "your little wins matter",
  "you are made of warm light",
  "go slow, still go",
  "you are allowed to rest",
  "cutie, the world needs your spark",
  "your heart is doing its best",
  "you look like hope today",
  "one song, one softer breath",
  "you are quietly becoming",
  "keep shining in your own way",
  "your energy feels like sunrise",
  "cutie, you are enough already",
  "let the beat hold you",
  "you are stronger in silence too",
  "your future self is cheering",
  "you make ordinary feel special",
  "you deserve soft things",
  "tiny progress is still progress",
  "your mood can bloom again",
  "cutie, stay close to your joy",
  "you have survived every hard day",
  "your calm is coming back",
  "you are not behind",
  "your presence is a little magic",
  "keep choosing yourself gently",
  "you are a whole cozy feeling",
  "you carry a beautiful kind of light",
  "your dreams are not silly",
  "cutie, breathe and begin again",
  "you make the night less lonely",
  "your softness is powerful",
  "good things can find you",
  "you are worth the wait",
  "let this song clean the noise",
  "your pace is still valid",
  "you are a sweet little miracle",
  "the hard part will pass",
  "you do not need to rush",
  "cutie, your vibe is precious",
  "you are learning, not failing",
  "your glow is coming back",
  "stay gentle with your mind",
  "you have a soft kind of courage",
  "this moment can be lighter",
  "you are more than the bad day",
  "your heart deserves music",
  "cutie, keep your little spark",
  "you are doing brave things quietly",
  "your kindness looks good on you",
  "you are allowed to feel better",
  "your story is still opening",
  "you are loved in little ways",
  "the universe saved this beat for you",
  "cutie, you are a warm vibe",
  "you can restart as many times",
  "your tired self still counts",
  "you bring poetry to small moments",
  "keep your heart cozy",
  "you are not too much",
  "you are not too late",
  "soft days are still productive",
  "you are someone's good thought",
  "cutie, your light has range",
  "you deserve peace without earning it",
  "your laugh belongs in this song",
  "you can make it through this verse",
  "your soul knows the way",
  "keep your hope hydrated",
  "you are quietly iconic",
  "this glow looks good on you",
  "cutie, keep blooming weirdly",
  "you are built from little victories",
  "your calm can return slowly",
  "you are a playlist of good things",
  "do it scared, do it softly",
  "you make the room feel kinder",
  "your effort is beautiful",
  "cutie, no need to prove it",
  "you are more loved than you notice",
  "your best is allowed to change",
  "one breath can change the color",
  "you are a cozy main character",
  "keep going, future legend",
  "your little heart is precious",
  "you deserve a good surprise",
  "the sky would save you a seat",
  "cutie, you are pure good weather",
  "you do not have to carry everything",
  "your softness survived so much",
  "you can be proud quietly",
  "let the rhythm untangle you",
  "you are not alone in this minute",
  "your peace is worth protecting",
  "cutie, your dreams have sparkle",
  "you are closer than yesterday",
  "you make silence feel warm",
  "your next chapter has flowers",
  "you can rest and still rise",
  "you are a soft little victory",
  "this song likes you back",
  "cutie, let your shoulders drop",
  "you are beautifully unfinished",
  "your glow does not need permission",
  "keep the tender part alive",
  "you are a mood worth saving",
  "your hope is still breathing",
  "tiny joy, big magic",
  "cutie, you are doing okay",
  "you have a gentle kind of power",
  "your heart is not a burden",
  "good days can start small",
  "you are worth soft music",
  "your light can flicker and stay",
  "cutie, keep your wonder close",
  "you are a calm little cosmos",
  "you can begin from here",
  "your feelings can move through",
  "you are not broken, just tired",
  "the beat is carrying you",
  "you deserve a little sweetness",
  "cutie, your aura is kind",
  "you are becoming your own safe place",
  "your courage can be quiet",
  "you make hope look cute",
  "keep your softness loud inside",
  "you are more capable than today says",
  "your vibe is moonlight-level pretty",
  "cutie, keep orbiting joy",
  "you can slow down and still win",
  "your smile has healing energy",
  "you are a good thing happening",
  "let this minute be kind",
  "your heart deserves gentle edits",
  "cutie, you are the soft plot twist",
  "you are doing the invisible work",
  "your glow is not gone",
  "you can choose peace again",
  "you are made for brighter rooms",
  "your tiny brave is enough",
  "cutie, stay golden in small ways",
  "you are a whole little sunrise",
  "your mind deserves less noise",
  "you can be soft and unstoppable",
  "good things are still possible",
  "you make this song warmer",
  "cutie, your energy is rare",
  "you are allowed to be proud",
  "your dream deserves patience",
  "you are a gentle force",
  "this second is not the whole story",
  "you carry light into corners",
  "cutie, keep your heart open",
  "you are someone's secret comfort",
  "your effort is not wasted",
  "you can glow after the rain",
  "you are worthy on quiet days",
  "your mood can lift softly",
  "cutie, take the win",
  "you are a brave little melody",
  "your peace can come in waves",
  "you have a lovable kind of chaos",
  "today is better with you in it",
  "your softness makes you real",
  "cutie, do not dim for the room",
  "you are allowed to need time",
  "your future is smiling somewhere",
  "you can hold hope lightly",
  "you are a small wonder",
  "your heart knows soft directions",
  "cutie, this glow belongs to you",
  "you are magic in normal clothes",
  "your progress has a heartbeat",
  "you can be gentle and brave",
  "let the next beat reset you",
  "you are a cute little comeback",
  "cutie, keep your crown invisible",
  "you are still becoming beautiful",
  "your vibe says healing",
  "you deserve a softer evening",
  "you can keep going without rushing",
  "your heart is a tiny lantern",
  "cutie, the night is proud of you",
  "you are tomorrow's favorite",
];

export default moodTexts;
